version: '3.7'
services:
  psmongodb:
    build: ./mongodb
    image: 192.168.253.28/portal-sale/mongodb:latest
    container_name: sale-db

  back:
    build: ./back
    image: 192.168.253.28/portal-sale/back:latest
    container_name: sale-back
    environment:
      - TMS_APP_PORT=3000
      - TMS_APP_NAME=dev-op
      - TMS_APP_LOG4JS_LEVEL=debug
      - TMS_MONGODB_USER_NAME=root
      - TMS_MONGODB_USER_PWD=pmjswjkai
    command:
      ['sh', './wait-for.sh', 'psmongodb:27017', '-t', '300', '--', 'node', 'server']

  admin:
    build: 
      context: ./ue_admin
      args:
        vue_app_base_url: /sale/admin
        vue_app_auth_base: /sale/auth
        vue_app_api_base: /sale/api
    image: 192.168.253.28/portal-sale/admin:latest
    container_name: sale-admin
    environment:
      - NGINX_WEB_BASE_URL=/sale/admin


  mongo:
    build: 
      context: ./ue_portal
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_base_url: /sale/portal
        vue_app_auth_base: /sale/auth
        vue_app_api_base: /sale/api
        vue_app_auth_disabled: 'No'
    image: 192.168.253.28/portal-sale/mongo:latest
    container_name: sale-mongo
    environment:
      - NGINX_WEB_BASE_URL=/sale/portal

  
