version: '3.7'
services:
  psmongodb:
    build: ./mongodb
    image: tms-portal-sale/mongo:latest
    container_name: portal-sale-mongo

  back:
    build: ./back
    image: tms-portal-sale/back:latest
    container_name: portal-sale-back
    environment:
      - TMS_APP_PORT=3000
      - TMS_APP_NAME=dev-op
      - TMS_APP_LOG4JS_LEVEL=debug
      - TMS_MONGODB_HOST=psmongodb
      - TMS_MONGODB_PORT=27017
      - TMS_MONGODB_USER_NAME=bss
      - TMS_MONGODB_USER_PWD=123456
    command:
      ['sh', './wait-for.sh', 'psmongodb:27017', '-t', '300', '--', 'node', 'server']

  ue_admin:
    build: 
      context: ./ue_admin
      args:
        vue_app_base_url: /sale/admin
        vue_app_base_api_base: /sale/api
    image: tms-portal-sale/ue_admin:latest
    container_name: portal-sale-ue_admin
    environment:
      - NGINX_WEB_BASE_URL=/sale/admin


  ue_portal:
    build: 
      context: ./ue_portal
      args:
        vue_app_login_key_username: username
        vue_app_login_key_password: password
        vue_app_login_key_pin: pin
        vue_app_base_url: /sale/portal
        vue_app_back_auth_base: /sale/auth
        vue_app_back_api_base: /sale/api
        vue_app_auth_disabled: 'No'
    image: tms-portal-sale/ue_portal:latest
    container_name: portal-sale-ue_portal
    environment:
      - NGINX_WEB_BASE_URL=/sale/portal

  
